nonrestartcalls=["pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,filename=fileLocation+bulkname,outputdir=outputLocation+'/'+REPLACEINDEX+'_')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,outputfile=outputLocation+REPLACEINDEX+'_outputfiletest.png',nooverwrite=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,outputfile=outputLocation+REPLACEPREVINDEX+'_outputfiletest.png',nooverwrite=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,filedir=fileLocation,step=REPLACETIME,run=verifydir+REPLACEINDEX)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,cellids=REPLACECELLID)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,coordinates=REPLACECOORDINATES)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,cellids=REPLACEMULTIPLECELLID)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,coordinates=REPLACEMULTIPLECOORDINATES)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,coordre=REPLACEMULTIPLECOORDRE)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,thick=0.5)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,thick=2.0)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,tickinterval=10)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,tickinterval=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,tickinterval=0.5,axisunit=6)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,tickinterval=1,axisunit=6)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,title='msec')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,title='musec')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,wmarkb=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,wmark='NE')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,wmark='NW')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,wmark='SE')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,wmark='SW')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,title=r'$\mathcal{Title}$ and so forth $\odot$')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,title='')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,filename=fileLocation+bulkname,run=verifydir+REPLACEINDEX,step=REPLACETIME)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,filename=fileLocation+bulkname,run=verifydir+REPLACEINDEX)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,vmin=7.e3,vmax=7.e6)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,vmin=7.e-3,vmax=7.e0)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,vmin=7.e6,vmax=7.e9)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,axisunit=3)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,axisunit=6)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,axisunit=0)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,fmin=1.e-14,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,fmax=1.e-12,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,fmin=1.e-14,fmax=1.e-12,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,setThreshold=1.e-20,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,setThreshold=1.e-15,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,setThreshold=0,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,cbulk=1,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,center=[-7e5,0,0],coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,center=[2e5,2e5,2e5],coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,xy=1,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,normal=[0,0,5],coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,xz=1,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,normal=[0,1,0],coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,yz=1,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,normal=[-1,0,0],coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,bpara=1,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,bperp=1,coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,normal=[1,1,1],coordre=REPLACECOORDRE)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,lin=1,vmax=50)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,lin=1,vmin=2,vmax=40)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,lin=1,vmin=0)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,lin=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,vmin=1,vmax=20,lin=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,filename=fileLocation+bulkname,run=verifydir+REPLACEINDEX,lin=1)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,vmin=0.1,vmax=10)",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,lin=1,vmin=0.5,vmax=1.5)"]

restartcalls=[]

multipopcalls=["pt.plot.plot_vdf_profiles(vlsvobj=f,run=verifydir+REPLACEINDEX,pop='REPLACEPOP',coordre=REPLACECOORDRE)"]

v5restartcalls=[]

v5nonrestartcalls=["pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,normal='x')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,normal='y')",
"pt.plot.plot_vdf_profiles(coordre=REPLACECOORDRE,vlsvobj=f,run=verifydir+REPLACEINDEX,normal='z')"]

v5multipopcalls=[]

